/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MyNFT__factory } from "./MyNFT__factory";
export { NFTMarketplace__factory } from "./NFTMarketplace__factory";
