// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqblpreardafoedogxmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxYmxwcmVhcmRhZm9lZG9neG1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNzM3MTksImV4cCI6MjA2MDc0OTcxOX0.1eiUATNsJuw6kiroYM8S2htW5RMJHSgnIucsSezPGDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
